// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BingNew.DataAccessLayer.Entities
{
    public partial class Article
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        public string Title { get; set; }
        public string ImgUrl { get; set; }
        public string Description { get; set; }
        public DateTime PubDate { get; set; }
        public string Url { get; set; }
        public int LikeNumber { get; set; }
        public int DisLikeNumber { get; set; }
        public int ViewNumber { get; set; }
        public int CommentNumber { get; set; }
        public string ProviderId { get; set; }
        public string TopicId { get; set; }
    }
}