// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BingNew.DataAccessLayer.Entities
{
    public partial class Topic
    {
        public Topic()
        {
            TopicFollow = new HashSet<TopicFollow>();
        }

        public string Id { get; set; }
        public string TopicName { get; set; }

        public virtual ICollection<TopicFollow> TopicFollow { get; set; }
    }
}